### ISSUE TITLE
Issue with Passive Investor Excel tzinfo datetime/time object is not set to None

### ISSUE THREAD

**Issue by Dabs212** [JerBouma/ThePassiveInvestor#6]
OS Windows10
---------------------------
Error
---------------------------
The program has crashed with the following error: 

Excel does not support timezones in datetimes. The tzinfo in the datetime/time object must be set to None.

If the problem persists, please create an Issue with the error message on the project's GitHub page:https://github.com/JerBouma/ThePassiveInvestor/issues.

**Comment by JerBouma** [comment]
I've retired the program due to the fact maintaining is not possible. I've updated the package to reflect the changes in `yfinance`. Please use the package instead, this should work!

**Comment by Dabs212** [comment]
Thanks for the update! Do we hve to reinstall the program to make it work or use it directly as is?

**Comment by JerBouma** [comment]
The program itself has been deprecated so the only way to use the package now is directly though Python. See: https://github.com/JerBouma/ThePassiveInvestor#installation. It could be that you need to type `pip install thepassiveinvestor -U` instead of `pip install thepassiveinvestor` to update to the latest version.

**Comment by Dabs212** [comment]
Thanks, after -U option progrma seems to act normal and working!! Yeh. May I ask how you fixed Tz zone issue?
